wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.1
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697211408.056299
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 17
      - 23
      - 37
      4: 3.9.1
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
device:
  desc: null
  value: cuda
epoches:
  desc: null
  value: 1
image_height:
  desc: null
  value: 128
patch_width:
  desc: null
  value: 16
use_cocotext:
  desc: null
  value: false
cocotext_path:
  desc: null
  value: /data/users/amolina/OCR/COCOText
use_esposalles:
  desc: null
  value: true
esposalles_path:
  desc: null
  value: /data/users/amolina/OCR/ESPOSALLES
use_funsd:
  desc: null
  value: false
funsd_path:
  desc: null
  value: /data/users/amolina/OCR/FUNSD
use_hiertext:
  desc: null
  value: false
hiertext_path:
  desc: null
  value: /data/users/amolina/OCR/HierText
use_hist_maps:
  desc: null
  value: false
hist_maps_path:
  desc: null
  value: /data/users/amolina/OCR/HistoricalMaps
use_iam:
  desc: null
  value: false
iam_path:
  desc: null
  value: /data/users/amolina/OCR/IAM
use_iiit:
  desc: null
  value: false
iiit_path:
  desc: null
  value: /data/users/amolina/OCR/IIIT5K/
use_mlt:
  desc: null
  value: false
mlt_path:
  desc: null
  value: /data/users/amolina/OCR/MLT19/
use_parzival:
  desc: null
  value: false
parzival_path:
  desc: null
  value: /data/users/amolina/OCR/Parzival
use_saint_gall:
  desc: null
  value: false
saint_gall_path:
  desc: null
  value: /data/users/amolina/OCR/SaintGall
use_sroie:
  desc: null
  value: false
sroie_path:
  desc: null
  value: /data/users/amolina/OCR/SROIE
use_svt:
  desc: null
  value: true
svt_path:
  desc: null
  value: /data/users/amolina/OCR/SVT
use_textocr:
  desc: null
  value: false
textocr_path:
  desc: null
  value: /data/users/amolina/OCR/TextOCR
use_totaltext:
  desc: null
  value: false
totaltext_path:
  desc: null
  value: /data/users/amolina/OCR/TotalText
use_washington:
  desc: null
  value: false
washington_path:
  desc: null
  value: /data/users/amolina/OCR/GW
use_xfund:
  desc: null
  value: false
xfund_path:
  desc: null
  value: /data/users/amolina/OCR/xFUND
mlt19_langs:
  desc: null
  value:
  - Arabic
  - Latin
  - Chinese
  - Japanese
  - Korean
  - Bangla
  - Hindi
  - Symbols
  - Mixed
  - None
xfund_langs:
  desc: null
  value:
  - ZH
  - JA
  - ES
  - FR
  - IT
  - DE
  - PT
cocotext_langs:
  desc: null
  value:
  - english
  - not english
cocotext_visibility:
  desc: null
  value:
  - legible
hiertext_handwritten:
  desc: null
  value:
  - 'true'
  - 'false'
hiertext_include_non_visible:
  desc: null
  value: false
esposalles_level:
  desc: null
  value: words
hiertext_level:
  desc: null
  value: words
iam_level:
  desc: null
  value: words
washington_level:
  desc: null
  value: word
parzival_level:
  desc: null
  value: word
esposalles_cross_validation_fold:
  desc: null
  value: cv1
washington_cross_validation_fold:
  desc: null
  value: cv1
mlt19_cross_validation_fold:
  desc: null
  value: cv1
hist_maps_cross_validation_fold:
  desc: null
  value: cv1
tokenizer_name:
  desc: null
  value: char_tokenizer
tokenizer_location:
  desc: null
  value: tmp_/tokenizers/
save_tokenizer:
  desc: null
  value: true
num_workers_train:
  desc: null
  value: 12
num_workers_test:
  desc: null
  value: 6
batch_size:
  desc: null
  value: 224
standarize:
  desc: null
  value: false
linear_model:
  desc: null
  value: true
model_depth:
  desc: null
  value: 6
model_width:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.1
token_size:
  desc: null
  value: 224
visual_tokenizer_depth:
  desc: null
  value: 0
visual_tokenizer_width:
  desc: null
  value: 224
load_checkpoint:
  desc: null
  value: false
checkpoint_name:
  desc: null
  value: null
